version: '3.4'

services:
  fileprocessingservice.api:
    image: ${DOCKER_REGISTRY-}fileprocessingserviceapi
    build:
      context: .
      dockerfile: Server/FileProcessingService.API/Dockerfile
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Congree!@#123"
        ACCEPT_EULA: "Y"